source: "rtsp://admin:elipse2025@192.168.1.108:554/cam/realmonitor?channel=1&subtype=0"

model: yolov8n.pt
conf: 0.4
iou: 0.5
rotate_deg: 0

display:
  show: true
  show_ids: true
  draw_head: true
  draw_line: true

snapshots:
  enabled: true
  dir: "C:/people_counter/snapshots"

backend:
  url: "http://127.0.0.1:8000"
  camera_id: "CAM-PC-01"

line:
  pos: 0.5
  arm_px: 80
  cross_tol_px: 18
  min_box_h_px: 110
  dir_lr: "in"
  dir_rl: "out"

unique:
  track_ttl_seconds: 25
  
sqlite_path: "people_counter.db"

unus:
  base_url: "https://unus.cl/WS_RECIBE_MOVIMIENTOS/wsRecibeMovimientos.asmx"
  base_datos_cliente: "CASI_COEXPAN"
  casi_cod: "001"
  lect_cod: "A"
  pass: "M1"
  timeout: 15